version: '3'
volumes:
  db: {}
services:
  api:
    image: kun391/phpup:3.0
    ports:
      - 9000:80
    depends_on:
      - db
    volumes:
      - .:/var/www/app
      - ./deployment/configs/queue.conf:/etc/supervisor/conf.d/queue.conf
    environment:
      - PHP_MEM_LIMIT=2048M
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: user123
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9029:80
    depends_on:
      - db
    environment:
      UPLOAD_LIMIT: 512M
      MAX_EXECUTION_TIME: 500
      PMA_HOSTS: db
      PMA_USER: dbuser
      PMA_PASSWORD: user123
