<?php


namespace App\Utils;

class ErrorCodeTransform
{
    const ERROR_CODE = [
        'accepted' => 'NAL-LOG-100',
        'accepted_if' => 'NAL-LOG-101',
        'active_url' => 'NAL-LOG-102',
        'after' => 'NAL-LOG-103',
        'after_or_equal' => 'NAL-LOG-104',
        'alpha' => 'NAL-LOG-105',
        'alpha_dash' => 'NAL-LOG-106',
        'alpha_numeric' => 'NAL-LOG-107',
        'array' => 'NAL-LOG-108',
        'bail' => 'NAL-LOG-109',
        'before' => 'NAL-LOG-110',
        'before_or_equal' => 'NAL-LOG-111',
        'between' => 'NAL-LOG-112',
        'boolean' => 'NAL-LOG-113',
        'confirmed' => 'NAL-LOG-114',
        'current_password' => 'NAL-LOG-115',
        'date' => 'NAL-LOG-116',
        'date_equals' => 'NAL-LOG-117',
        'date_format' => 'NAL-LOG-118',
        'different' => 'NAL-LOG-119',
        'digits' => 'NAL-LOG-120',
        'digits_between' => 'NAL-LOG-121',
        'dimensions' => 'NAL-LOG-122',
        'distinct' => 'NAL-LOG-123',
        'email' => 'NAL-LOG-124',
        'ends_with' => 'NAL-LOG-125',
        'exclude_if' => 'NAL-LOG-126',
        'exclude_unless' => 'NAL-LOG-127',
        'exists' => 'NAL-LOG-128',
        'file' => 'NAL-LOG-129',
        'filled' => 'NAL-LOG-130',
        'greater_than' => 'NAL-LOG-131',
        'greater_than_or_equal' => 'NAL-LOG-132',
        'image' => 'NAL-LOG-133',
        'in' => 'NAL-LOG-134',
        'in_array' => 'NAL-LOG-135',
        'integer' => 'NAL-LOG-136',
        'ip_address' =>  'NAL-LOG-137',
        'json' => 'NAL-LOG-138',
        'less_than' => 'NAL-LOG-139',
        'less_than_or_equal' => 'NAL-LOG-140',
        'max' => 'NAL-LOG-141',
        'mime_types' => 'NAL-LOG-142',
        'mime_type_by_file_extension' => 'NAL-LOG-143',
        'min' => 'NAL-LOG-144',
        'multiple_of' => 'NAL-LOG-145',
        'not_in' => 'NAL-LOG-146',
        'not_regex' => 'NAL-LOG-147',
        'nullable' => 'NAL-LOG-148',
        'numeric' => 'NAL-LOG-149',
        'password' => 'NAL-LOG-150',
        'present' => 'NAL-LOG-151',
        'prohibited' => 'NAL-LOG-152',
        'prohibited_if' => 'NAL-LOG-153',
        'prohibited_unless' => 'NAL-LOG-154',
        'regular_expression' => 'NAL-LOG-155',
        'required' => 'NAL-LOG-156',
        'required_if' => 'NAL-LOG-157',
        'required_unless' => 'NAL-LOG-158',
        'required_with' => 'NAL-LOG-159',
        'required_with_all' => 'NAL-LOG-160',
        'required_without' => 'NAL-LOG-161',
        'required_without_all' => 'NAL-LOG-162',
        'same' => 'NAL-LOG-163',
        'size' => 'NAL-LOG-164',
        'sometimes' => 'NAL-LOG-165',
        'starts_with' => 'NAL-LOG-166',
        'string' => 'NAL-LOG-167',
        'timezone' => 'NAL-LOG-168',
        'unique' => 'NAL-LOG-169',
        'url' => 'NAL-LOG-170',
        'uuid' => 'NAL-LOG-171',
    ];
}
